name: EshopApi

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        ports:
            - "9000:9000" #API
            - "9001:9001" #Console
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=Welcome123!
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001" #Assigne a folder to use

volumes:
    minio_data: